# Generated by Django 3.2.15 on 2022-08-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='image.jpg', upload_to='images/uploads/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'My Profile',
                'verbose_name_plural': 'My Profiles',
                'db_table': 'my_profile',
            },
        ),
    ]
